from PIL import Image,ImageChops
from pathlib import Path
import hashlib,json
src=Path('art/sources/chapter1/objects');dest=Path('game/assets/chapter1/objects');rev=Path('art/reviews/chapter1/objects');p=dest/'object_metadata.json';meta=json.loads(p.read_text());meta['assets']=[a for a in meta['assets'] if a['asset_id'] not in ['asset.object.chapter1.farmhouse_blue','asset.object.chapter1.chicken_coop','asset.object.chapter1.wood_sign']]
for name,original,job in [('farmhouse_blue','farmhouse_original.png','e321013e-69b9-49ff-bfe7-838ccd8972a5'),('chicken_coop','doghouse_generated.png','bcc45a5e-46ec-4cf3-a1ed-54bb21def8c0')]:
 im=Image.open(src/f'{name}.png').convert('RGBA');im.save(dest/f'{name}.png');w,h=im.size
 row={'asset_id':f'asset.object.chapter1.{name}','runtime_path':str(dest/f'{name}.png'),'source_path':str(src/f'{name}.png'),'source_sha256':hashlib.sha256((src/f'{name}.png').read_bytes()).hexdigest(),'sha256':hashlib.sha256((dest/f'{name}.png').read_bytes()).hexdigest(),'size_px':[w,h],'anchor_px':[96,149] if name=='farmhouse_blue' else [w//2,h-2],'original_source_path':str(src/original),'original_source_sha256':hashlib.sha256((src/original).read_bytes()).hexdigest(),'pixel_tool_id':job,'review_status':'proposed','reviewer':None,'usage':'environment_only','world_scale':1,'license_note':'Derived project original/PixelLab source; exact native free pixelart_workbench edits','drive_url':None,'processing':'LibreSprite native compound-gable refinement; see farmhouse_pixel_refine.js and editable ASE source' if name=='farmhouse_blue' else 'kennel shell reused; half-door rail and 3 vent slats, exact native brush editing'}
 if name=='farmhouse_blue':
  assert im.size == (192,152); assert set(im.getchannel('A').getdata()) == {0,255}; split=104
  row['validation']='native LibreSprite refinement, same canvas/anchor and binary alpha; layers recompose exactly'
 else:split=42
 back=im.copy();front=im.copy();back.paste((0,0,0,0),(0,0,w,split));front.paste((0,0,0,0),(0,split,w,h));back.save(dest/f'{name}_body.png');front.save(dest/f'{name}_roof.png');assert Image.alpha_composite(back,front).tobytes()==im.tobytes();row['layers']={'body':str(dest/f'{name}_body.png'),'roof':str(dest/f'{name}_roof.png')};row['layer_split_y_px']=split
 im.resize((w*8,h*8),Image.Resampling.NEAREST).save(rev/f'{name}_8x.png');meta['assets'].append(row)
board=Image.open(dest/'tool_bench.png').convert('RGBA');post=Image.open(dest/'fence_post.png').convert('RGBA');out=Image.new('RGBA',(48,64));out.alpha_composite(post,(15,24));out.alpha_composite(board.crop((24,6,72,22)),(0,9));out.save(src/'wood_sign.png');out.save(dest/'wood_sign.png');out.resize((384,512),Image.Resampling.NEAREST).save(rev/'wood_sign_8x.png')
meta['assets'].append({'asset_id':'asset.object.chapter1.wood_sign','runtime_path':str(dest/'wood_sign.png'),'source_path':str(src/'wood_sign.png'),'sha256':hashlib.sha256((dest/'wood_sign.png').read_bytes()).hexdigest(),'size_px':[48,64],'anchor_px':[24,64],'review_status':'proposed','reviewer':None,'usage':'environment_only','processing':'Exact existing tool bench board crop[24,6,72,22] over fence_post at[15,24]; no text or resampling','source_components':[str(dest/'tool_bench.png'),str(dest/'fence_post.png')],'license_note':'Derived from own PixelLab task sources'})
meta['crop_status_mapping']={'untilled':{'plant_path':None},'tilled':{'plant_path':None},'growing':{'plant_path':None,'status':'missing; no accepted radish PNG'},'mature':{'plant_path':None,'status':'missing; radish generator returned a stump and was rejected'},'harvest':{'plant_path':None,'note':'command returns existing PlotState to tilled; no durable harvest state'}}
p.write_text(json.dumps(meta,indent=2)+'\n')
print('Derived farmhouse/coop metadata and exact layer recomposition verified')
