from pathlib import Path
from PIL import Image
import hashlib,json
src=Path('art/sources/chapter1/objects');dest=Path('game/assets/chapter1/objects');rev=Path('art/reviews/chapter1/objects');p=dest/'object_metadata.json';meta=json.loads(p.read_text());meta['assets']=[a for a in meta['assets'] if a['asset_id'] not in ['asset.object.chapter1.radish_growing','asset.object.chapter1.radish_mature']]
for state,job,tool in [('growing','1de8274e-b20c-45cb-9dd2-2c149d2fa604','fa2a33d0-0550-4914-b959-c93800406133'),('mature','8ec2c715-1b67-43f4-910f-c4be0df539c1','09977592-fc06-4629-9f33-28f6ff3fe9d1')]:
 name='radish_'+state;im=Image.open(src/f'{name}_clean.png').convert('RGBA');box=im.getbbox();out=Image.new('RGBA',(32,32));shift=32-box[3];out.alpha_composite(im,(0,shift));out.save(dest/f'{name}.png');out.resize((256,256),Image.Resampling.NEAREST).save(rev/f'{name}_8x.png')
 meta['assets'].append({'asset_id':f'asset.object.chapter1.{name}','runtime_path':str(dest/f'{name}.png'),'source_path':str(src/f'{name}_clean.png'),'original_source_path':str(src/f'{name}.png'),'original_source_sha256':hashlib.sha256((src/f'{name}.png').read_bytes()).hexdigest(),'source_sha256':hashlib.sha256((src/f'{name}_clean.png').read_bytes()).hexdigest(),'sha256':hashlib.sha256((dest/f'{name}.png').read_bytes()).hexdigest(),'size_px':[32,32],'anchor_px':[16,32],'crop_status':state,'usage':'existing_crop.radish_visual_only','review_status':'proposed','reviewer':None,'source_vertical_translation_px':shift,'alpha_values':sorted(set(out.getchannel('A').get_flattened_data())),'opaque_color_count':len(set(c for c in out.get_flattened_data() if c[3])),'job_id':job,'pixel_tool_id':tool,'palette_reference_path':str(src/'reference_radish.png'),'palette_reference_sha256':hashlib.sha256((src/'reference_radish.png').read_bytes()).hexdigest(),'processing':'Free guarded pixel cleanup removed growing bare roots and reduced both sprites to <=24 existing source colors; integer translation to shared foot anchor only; no resizing','license_note':'PixelLab ordinary PixFlux generation, project approved original reference palette; no soil, economics or gameplay changes','drive_url':None})
meta['crop_status_mapping']={'untilled':{'plant_path':None},'tilled':{'plant_path':None},'growing':{'plant_path':'game/assets/chapter1/objects/radish_growing.png'},'mature':{'plant_path':'game/assets/chapter1/objects/radish_mature.png'},'harvest':{'plant_path':None,'note':'Command transitions real PlotState to tilled, not a durable crop state'}}
p.write_text(json.dumps(meta,indent=2)+'\n')
print('Radish growing/mature: shared32x32 canvas, anchor16,32, plant only')
